### ISSUE TITLE
Question: Tailwind applyBaseStyles

### ISSUE THREAD

**Issue by alexookah** [JustGoodUI/dante-astro-theme#33]
Very nice work for the theme!
I really like it!
I was wondering why have you configured `applyBaseStyles: false` ?

**Comment by astab** [comment]
Thank you!
`applyBaseStyles` is set to `false` to avoid duplicate injection of tailwind styles. You can read more about it here: https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles .

**Comment by alexookah** [comment]
I tried to add some 404 error page.
and had some troubles adjusting some spacings. I had to enable the applyBaseStyles to make it work. Would it break something enabling it?
