### ISSUE TITLE
Font flickers to first load

### ISSUE THREAD

**Issue by rkondratowicz** [JustGoodUI/dante-astro-theme#46]
When viewing the page for the first time, the font changes from one to another.

To reproduce: do a hard refresh in the browser. (For example cmd+shift+r on macos in chrome)

**Comment by astab** [comment]
Thank you for bringing this up. I’ve made improvements by switching to local fonts and adding font preloading links. These changes should enhance performance and provide a better user experience.

**Comment by dandv** [comment]
Thank you for this fix! I noticed a similar issue with [this theme](https://github.com/michael-andreuzza/microblog/issues/2).

And congrats on the fastest Astro theme I've found yet! Surprising that so many other Astro themes, even official ones like [portfolio](https://github.com/withastro/astro/issues/10311) suffer from suboptimal performance (at least on Firefox) when [navigating among site pages](https://github.com/one-aalam/astro-ink/issues/63).

**Comment by dandv** [comment]
Actually, now I notice that each click takes about 1-2 seconds to load the page, for example from https://dante-astro-theme.netlify.app/blog/ to any blog post. Gatsby's preloading makes these clicks instant. Thoughts?
